apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-frontend
  namespace: tasktracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker-frontend
  template:
    metadata:
      labels:
        app: tasktracker-frontend
    spec:
      containers:
        - name: frontend
          image: ankitaubale/tasktracker-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
